version: '3.3'
services:
  db:
    image: mysql:latest
    volumes: 
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine

  redmine:
    depends_on:
      - db 
    image: redmine:latest
    ports: 
      - "8080:3000"
    restart: always
    environment:
      REDMINE_DB_HOST: db:3306
      REDMINE_DB_USER: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_NAME: redmine

volumes:
  db_data: {}
